// Usage: node scripts/desktop-check.mjs (against http://localhost:8000)
import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
const wait = (ms) => new Promise((r) => setTimeout(r, ms))
await page.goto('http://localhost:8000/', { waitUntil: 'networkidle' })
await wait(2500)
console.log('map canvas', await page.locator('.map-host canvas').count(), 'map status', (await page.locator('.map-status').textContent().catch(() => '-'))?.trim().slice(0, 40))
await page.goto('http://localhost:8000/kanji/%E6%B0%B8', { waitUntil: 'networkidle' })
await wait(1200)
console.log('graph nodes', await page.locator('.graph-svg .node').count(), 'zoom buttons', await page.locator('.map-zoom button').count(), 'lock', await page.locator('.graph-lock').count())
const t0 = await page.locator('.graph-svg > g').first().getAttribute('transform')
await page.mouse.move(700, 450); await page.mouse.down(); await page.mouse.move(800, 500, { steps: 8 }); await page.mouse.up()
await wait(300)
console.log('drag moved graph', t0 !== (await page.locator('.graph-svg > g').first().getAttribute('transform')))
await page.mouse.wheel(0, -300); await wait(300)
console.log('wheel changed transform', t0 !== (await page.locator('.graph-svg > g').first().getAttribute('transform')))
await page.locator('.graph-svg .node[data-kind="component"]').first().click(); await wait(800)
console.log('clicked component -> page', (await page.locator('.page-head .detail-glyph').first().textContent())?.trim(), 'graph still on', (await page.locator('.graph-svg .node[data-kind="focus"] text').first().textContent())?.trim())
await page.fill('.search-input', 'water'); await wait(1200)
console.log('desktop word rows', await page.locator('.word').count())
await page.locator('.searchbar-tool').first().click(); await wait(800)
console.log('draw pad', await page.locator('.drawpad').count())
await page.keyboard.press('Escape')
await page.locator('.profile-button').first().click(); await wait(800)
console.log('account dialog', await page.locator('.overlay').count())
console.log('errors', errors)
await browser.close()
